version: "3.8"
services:
  web:
    depends_on:
      - api
    build: "./frontend"
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    develop:
      watch:
        - path: "./frontend/package.json"
          action: rebuild
        - path: "./frontend"
          action: rebuild
        - path: "./front-end/pnpm-lock.yaml"
          action: rebuild
  api:
    depends_on:
      - db

    build: ./backend

    ports:
      - 8000:8000

    environment:
      DB_URL: mongodb://db/anime

    develop:
      watch:
        - path: ./backend/package.json
          action: rebuild
        - path: ./backend/pnpm-lock.yaml
          action: rebuild

        - path: ./backend
          target: /app
          action: sync

  db:
    image: mongo:latest

    ports:
      - 27017:27017

    volumes:
      - anime:/data/db

volumes:
  anime:
